[versions]
codenarc = '3.6.0'
initializr = '0.22.0'
jacoco = '0.8.13'
spock = '2.3-groovy-4.0'
wiremock = '3.13.1'
pluginPublish = '1.3.1'

[libraries]
wiremock-jre8 = { module = 'org.wiremock:wiremock', version.ref = 'wiremock' }
