name: Feature Request
description: Suggest a feature or enhancement for the plugin.
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a feature!

  - type: textarea
    id: feature-description
    attributes:
      label: What is the feature you would like to propose?
      description: Provide a clear and concise description of the feature or enhancement.
      placeholder: A clear description of your feature request.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature needed?
      description: Please explain why this feature would be useful or what problem it would solve.
      placeholder: Describe the motivation behind this feature.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or workarounds you have considered.
      placeholder: Describe alternative approaches you have considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Additional context or relevant screenshots.
    validations:
      required: false
